# Face Mask Detection using Convolutional Neural Network (CNN)

## Project Overview

This project aims to build a Deep Learning model using Convolutional Neural Networks (CNN) to detect whether a person is wearing a face mask or not.
The model is trained on image data and can also perform real-time detection using a live camera.

## Problem Statement

During the COVID-19 pandemic, wearing a face mask became essential to prevent the spread of the virus. However,
monitoring mask compliance manually in public places is difficult.

The objective of this project is to develop a Deep Learning-based Face Mask Detection system that can automatically
classify whether a person is wearing a mask or not using image data and live video feed.

## Project Objectives

- To collect and preprocess image data for mask and no-mask categories.
- To build a CNN model for binary image classification.
- To train and evaluate the model for accuracy and performance.
- To implement real-time face mask detection using webcam.
- To analyze model performance using accuracy and loss metrics.

## Importing Required Libraries

In this section, we import all the necessary libraries required for image processing, model building, and visualization.

In [1]:
import os
import cv2
import matplotlib.pyplot as plt
import numpy as np
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense

### Explanation

- `os` → Used for file and directory operations.
- `cv2` → Used for image processing.
- `numpy` → Used for numerical computations.
- `matplotlib` → Used for visualization.
- `tensorflow.keras` → Used to build and train the CNN model.

In [2]:
path1=r"C:\Neural Networks\withmask_withoutmask"
cate=['with_mask','without_mask']
# create the path

## Data Loading and Preprocessing

In this section, we load the dataset, resize images, convert them into arrays, and normalize pixel values.

In [3]:
image_size=200
input_image=[]
for i in cate:
    folders=os.path.join(path1,i)
    label=cate.index(i)
    for image in os.listdir(folders):
        image_path=os.path.join(folders,image)
        image_array=cv2.imread(image_path)
        image_array=cv2.resize(image_array,(image_size,image_size))
        input_image.append([image_array,label])


### Explanation

- Images are resized to a fixed size for uniform input.
- Pixel values are normalized (0–255 → 0–1) to improve model performance.
- Labels are assigned: 
  - 1 → Without Mask
  - 0 → With Mask

In [4]:
len(input_image)

7553

In [5]:
np.random.shuffle(input_image)

In [6]:
train  = input_image[0:6000]
test   = input_image[6000::] 

X_train = []
Y_train = []

for X_values , labels in train: 

    X_train.append(X_values)

    Y_train.append(labels)

X_test = []

Y_test = []

for X_values , labels in train: 

    X_test.append(X_values)

    Y_test.append(labels)

In [7]:
X_train = np.array(X_train)

Y_train= np.array(Y_train)

X_test = np.array(X_test)

#Y_test= np.array(Y_test) # directly used in confusion matrix so no need to convert

In [8]:
X_train  = X_train / 255 

X_test  = X_test / 255

## Building the CNN Model

We create a Convolutional Neural Network model consisting of:
- Convolution layers for feature extraction
- MaxPooling layers for dimensionality reduction
- Dense layers for classification

In [9]:
import tensorflow as tf
import keras

In [10]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPool2D, Flatten, Dense

In [11]:
model = Sequential()
model.add(Conv2D(filters = 32 , kernel_size =(5,5) , activation ='relu'  ,padding='same'   ))
model.add(MaxPool2D(pool_size =(2,2)))
model.add(Flatten())
model.add(Dense(256 , activation = 'relu' , input_shape = X_train.shape[1:]))
model.add(Dense(2 , activation= 'softmax'))

C:\Users\Chinnarajan M\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### Explanation of CNN Layers

- **Conv2D** → Extracts important features from images.
- **MaxPooling2D** → Reduces spatial dimensions.
- **Flatten** → Converts 2D feature maps into 1D vector.
- **Dense** → Fully connected layer for classification.
- **Dropout** → Prevents overfitting.

## Model Training

The model is trained using training data and validated using validation data.

In [12]:
adam=tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(optimizer=adam,loss='sparse_categorical_crossentropy',metrics=['accuracy'])
model.fit(X_train,Y_train,epochs=5,batch_size=64,validation_split=0.2)

Epoch 1/5
75/75 ━━━━━━━━━━━━━━━━━━━━ 76s 826ms/step - accuracy: 0.7844 - loss: 2.5129 - val_accuracy: 0.8758 - val_loss: 0.3270
Epoch 2/5
75/75 ━━━━━━━━━━━━━━━━━━━━ 58s 768ms/step - accuracy: 0.9042 - loss: 0.2491 - val_accuracy: 0.8975 - val_loss: 0.2869
Epoch 3/5
75/75 ━━━━━━━━━━━━━━━━━━━━ 57s 767ms/step - accuracy: 0.9360 - loss: 0.1723 - val_accuracy: 0.8958 - val_loss: 0.2648
Epoch 4/5
75/75 ━━━━━━━━━━━━━━━━━━━━ 54s 722ms/step - accuracy: 0.9610 - loss: 0.1150 - val_accuracy: 0.9000 - val_loss: 0.2900
Epoch 5/5
75/75 ━━━━━━━━━━━━━━━━━━━━ 55s 734ms/step - accuracy: 0.9779 - loss: 0.0731 - val_accuracy: 0.9108 - val_loss: 0.3034


### Explanation

- The model learns patterns from images during training.
- Accuracy and loss are tracked for both training and validation datasets.
- Epochs determine how many times the model sees the entire dataset.

In [13]:
pred=model.predict(X_test)

188/188 ━━━━━━━━━━━━━━━━━━━━ 24s 112ms/step


In [14]:
pred_cate=np.argmax(pred,axis=1)

## Model Evaluation

The trained model is evaluated on test data to measure its performance.

In [15]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(Y_test,pred_cate))
print("-----------------------------------------------------")
print(classification_report(Y_test,pred_cate))

[[2868  100]
 [  54 2978]]
-----------------------------------------------------
              precision    recall  f1-score   support

           0       0.98      0.97      0.97      2968
           1       0.97      0.98      0.97      3032

    accuracy                           0.97      6000
   macro avg       0.97      0.97      0.97      6000
weighted avg       0.97      0.97      0.97      6000



### Evaluation Metrics

- **Accuracy** → Percentage of correct predictions.
- **Loss** → Error between predicted and actual values.

In [16]:
model.save("withmask_withoutmask.h5")

".h5 " is used in Keras/TensorFlow to save a trained deep learning model to a file
this code is preserving my trained neural network into a file called withmask_withoutmask.h5, which we can reload and reuse later.

## Real-Time Face Mask Detection (Live Camera)

Using OpenCV, we access the webcam and detect faces in real-time. The trained model predicts whether the detected face is wearing a mask or not.

In [17]:
import cv2
import numpy as np
from PIL import Image
from keras.models import load_model  #  used to load the pre trained model

In [18]:
def  face_extractor(img):

    faces = face_cascade.detectMultiScale(img, scaleFactor = 1.5 , minNeighbors = 5)

    if faces is ():

        return None

    

    

    for (x ,y , w, h)  in faces:

        cv2.rectangle(img , (x,y) , (x+w , y+h), (0,0, 255) , 2)

        roi =  img[y :y+h , x:x+w]

    

    return roi

<>:5: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
C:\Users\Chinnarajan M\AppData\Local\Temp\ipykernel_18136\2871236416.py:5: SyntaxWarning: "is" with 'tuple' literal. Did you mean "=="?
  if faces is ():


### Explanation

- Webcam captures live video frames.
- Face detection is performed using Haar Cascade.
- Each detected face is passed to the CNN model.
- Prediction is displayed on the screen.

In [19]:
face_cascade =  cv2.CascadeClassifier(r"C:\Users\Chinnarajan M\Downloads\haarcascade_frontalface_default.xml")

model = load_model("withmask_withoutmask.h5")  # name of pre trained model

 

video_capture =cv2.VideoCapture(0) #  camera 

while True:

    ret,frame = video_capture.read()

    

    face = face_extractor(frame)

    if type(face) is np.ndarray:

        face = cv2.resize(face , (200,200))

        im = Image.fromarray(face , 'RGB')

        

        

        img_array = np.array(im)

        

        img_array = np.expand_dims(img_array ,  axis = 0)

        pred = model.predict(img_array)  #  making the prediction

        print(pred)

        

        

        name = "None Matching"

 

        if pred[0][0]  > .5:

            name ="Masked"

        elif pred[0][1]  > .5:

            name = 'Mask is not there , Put on the mask' 

        cv2.putText(frame ,name , (75 , 75) , cv2.FONT_HERSHEY_COMPLEX , 1 , (255 , 0, 0) , 2)    

    else:

        cv2.putText(frame ,"Face not found" , (75 , 75 ) , cv2.FONT_HERSHEY_COMPLEX ,1 , (255 , 0, 0) , 2)

    cv2.imshow('Video' , frame)    

        

    if cv2.waitKey(20) & 0xff == ord('q') : 

        break

     

video_capture.release()

cv2.destroyAllWindows()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[[0. 1.]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step
[

## Results

The CNN model successfully classifies images into:
- With Mask
- Without Mask

The model achieved good accuracy on validation data and performs effectively in real-time detection.

## Conclusion

This project demonstrates how Deep Learning and Computer Vision can be used to solve real-world problems like mask compliance monitoring. 

The system can be further improved by:
- Using a larger dataset
- Applying data augmentation
- Using pre-trained models like MobileNet
- Deploying the model as a web or mobile application

## Future Enhancements

- Deploy the model using Flask or Streamlit.
- Integrate with CCTV systems.
- Improve accuracy using transfer learning.
- Add alert system for no-mask detection.